use deadlock_data::{Error, Result};

const SQL: &[(&str, &str)] = &[
    (
        "beam/select_item_counts.sql",
        include_str!("../sql/beam/select_item_counts.sql"),
    ),
    (
        "discovery/count_hero_appearances.sql",
        include_str!("../sql/discovery/count_hero_appearances.sql"),
    ),
    (
        "discovery/count_split_boundaries.sql",
        include_str!("../sql/discovery/count_split_boundaries.sql"),
    ),
    (
        "discovery/create_fixed_partitions.sql",
        include_str!("../sql/discovery/create_fixed_partitions.sql"),
    ),
    (
        "discovery/create_ranked_partitions.sql",
        include_str!("../sql/discovery/create_ranked_partitions.sql"),
    ),
    (
        "discovery/select_decision_rows.sql",
        include_str!("../sql/discovery/select_decision_rows.sql"),
    ),
    (
        "discovery/select_item_pool_purchases.sql",
        include_str!("../sql/discovery/select_item_pool_purchases.sql"),
    ),
    (
        "discovery/select_landmark_rows.sql",
        include_str!("../sql/discovery/select_landmark_rows.sql"),
    ),
    (
        "discovery/select_purchase_event_histories.sql",
        include_str!("../sql/discovery/select_purchase_event_histories.sql"),
    ),
    (
        "discovery/select_purchase_histories.sql",
        include_str!("../sql/discovery/select_purchase_histories.sql"),
    ),
    (
        "extract/attach_remote.sql",
        include_str!("../sql/extract/attach_remote.sql"),
    ),
    (
        "extract/attach_remote_snapshot.sql",
        include_str!("../sql/extract/attach_remote_snapshot.sql"),
    ),
    (
        "extract/count_hero_accounts.sql",
        include_str!("../sql/extract/count_hero_accounts.sql"),
    ),
    (
        "extract/count_heroes.sql",
        include_str!("../sql/extract/count_heroes.sql"),
    ),
    (
        "extract/count_purchase_net_worth.sql",
        include_str!("../sql/extract/count_purchase_net_worth.sql"),
    ),
    (
        "extract/count_table_rows.sql",
        include_str!("../sql/extract/count_table_rows.sql"),
    ),
    (
        "extract/count_team_lead.sql",
        include_str!("../sql/extract/count_team_lead.sql"),
    ),
    (
        "extract/create_compositions.sql",
        include_str!("../sql/extract/create_compositions.sql"),
    ),
    (
        "extract/create_decision_opportunities.sql",
        include_str!("../sql/extract/create_decision_opportunities.sql"),
    ),
    (
        "extract/create_ducklake_secret.sql",
        include_str!("../sql/extract/create_ducklake_secret.sql"),
    ),
    (
        "extract/create_eligible_matches.sql",
        include_str!("../sql/extract/create_eligible_matches.sql"),
    ),
    (
        "extract/create_first_purchases.sql",
        include_str!("../sql/extract/create_first_purchases.sql"),
    ),
    (
        "extract/create_hero_account_counts.sql",
        include_str!("../sql/extract/create_hero_account_counts.sql"),
    ),
    (
        "extract/create_item_assets.sql",
        include_str!("../sql/extract/create_item_assets.sql"),
    ),
    (
        "extract/create_match_folds.sql",
        include_str!("../sql/extract/create_match_folds.sql"),
    ),
    (
        "extract/create_player_matches.sql",
        include_str!("../sql/extract/create_player_matches.sql"),
    ),
    (
        "extract/create_player_snapshots.sql",
        include_str!("../sql/extract/create_player_snapshots.sql"),
    ),
    (
        "extract/create_purchases.sql",
        include_str!("../sql/extract/create_purchases.sql"),
    ),
    (
        "extract/create_s3_secret.sql",
        include_str!("../sql/extract/create_s3_secret.sql"),
    ),
    (
        "extract/create_source_snapshot.sql",
        include_str!("../sql/extract/create_source_snapshot.sql"),
    ),
    (
        "extract/create_split_boundaries.sql",
        include_str!("../sql/extract/create_split_boundaries.sql"),
    ),
    (
        "extract/create_team_snapshots.sql",
        include_str!("../sql/extract/create_team_snapshots.sql"),
    ),
    (
        "extract/detach_remote.sql",
        include_str!("../sql/extract/detach_remote.sql"),
    ),
    (
        "extract/drop_decision_opportunities.sql",
        include_str!("../sql/extract/drop_decision_opportunities.sql"),
    ),
    (
        "extract/drop_eligible_matches.sql",
        include_str!("../sql/extract/drop_eligible_matches.sql"),
    ),
    (
        "extract/drop_first_purchases.sql",
        include_str!("../sql/extract/drop_first_purchases.sql"),
    ),
    (
        "extract/drop_hero_account_counts.sql",
        include_str!("../sql/extract/drop_hero_account_counts.sql"),
    ),
    (
        "extract/drop_item_assets.sql",
        include_str!("../sql/extract/drop_item_assets.sql"),
    ),
    (
        "extract/drop_player_matches.sql",
        include_str!("../sql/extract/drop_player_matches.sql"),
    ),
    (
        "extract/drop_player_snapshots.sql",
        include_str!("../sql/extract/drop_player_snapshots.sql"),
    ),
    (
        "extract/drop_purchases.sql",
        include_str!("../sql/extract/drop_purchases.sql"),
    ),
    (
        "extract/drop_team_snapshots.sql",
        include_str!("../sql/extract/drop_team_snapshots.sql"),
    ),
    (
        "extract/export_table.sql",
        include_str!("../sql/extract/export_table.sql"),
    ),
    (
        "extract/fill_split_boundaries.sql",
        include_str!("../sql/extract/fill_split_boundaries.sql"),
    ),
    (
        "extract/insert_item_assets.sql",
        include_str!("../sql/extract/insert_item_assets.sql"),
    ),
    (
        "extract/load_extensions.sql",
        include_str!("../sql/extract/load_extensions.sql"),
    ),
    (
        "extract/select_current_snapshot.sql",
        include_str!("../sql/extract/select_current_snapshot.sql"),
    ),
    (
        "extract/select_source_snapshot.sql",
        include_str!("../sql/extract/select_source_snapshot.sql"),
    ),
    (
        "extract/set_memory_limit.sql",
        include_str!("../sql/extract/set_memory_limit.sql"),
    ),
    (
        "extract/set_temp_directory.sql",
        include_str!("../sql/extract/set_temp_directory.sql"),
    ),
    (
        "extract/set_threads.sql",
        include_str!("../sql/extract/set_threads.sql"),
    ),
    (
        "production/select_path_cohort_summary.sql",
        include_str!("../sql/production/select_path_cohort_summary.sql"),
    ),
    (
        "production/select_path_item_metrics.sql",
        include_str!("../sql/production/select_path_item_metrics.sql"),
    ),
];

pub fn load_sql(name: &str) -> Result<&'static str> {
    SQL.iter()
        .find_map(|(resource, sql)| (*resource == name).then_some(*sql))
        .ok_or_else(|| Error::new(format!("SQL resource does not exist: {name}")))
}
